name: ecommerce_store
description: "New Ecommerce Store"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  flutter_riverpod: ^2.5.1
  carousel_slider: ^5.1.1
  flutter_stripe: ^12.0.2
  flutter_dotenv: ^6.0.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
     - .env
     - res/images/Splash.png
     - res/images/Walkthrough_images/model1.png
     - res/images/Walkthrough_images/model2.png
     - res/images/Walkthrough_images/model3.png
     - res/Auth_Button/apple.svg
     - res/Auth_Button/google.svg
     - res/Auth_Button/facebook.svg
     - res/images/payments.svg
     - res/images/Card.svg
     - res/congratulation.json
     - res/images/successOrder.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: res/AppIcon/AppIcon.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
